import type { TransferReceipt } from '@/data/mutations'

export interface TransferReceiptPdfInput {
  receipt: TransferReceipt
  recipientLabel: string
  amountLabel: string
  fromIbanMasked: string
  toIbanMasked: string
  timestampLabel: string
}

interface PdfTextOptions {
  size?: number
  color?: string
  font?: 'regular' | 'bold'
}

interface PdfLineOptions {
  width?: number
  color?: string
}

const PAGE_WIDTH = 595.28
const PAGE_HEIGHT = 841.89
const MARGIN_X = 54
const FONT_REGULAR = 'F1'
const FONT_BOLD = 'F2'
const COLORS = {
  ink: '0.950 0.950 0.970',
  muted: '0.560 0.580 0.620',
  faint: '0.210 0.220 0.250',
  panel: '0.110 0.115 0.135',
  border: '0.235 0.245 0.275',
  brand: '0.910 0.430 0.180',
  success: '0.490 0.850 0.650',
}

export function downloadTransferReceiptPdf(input: TransferReceiptPdfInput): void {
  const pdf = createTransferReceiptPdf(input)
  const blob = new Blob([pdf], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = buildReceiptFileName(input.receipt)
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function createTransferReceiptPdf(input: TransferReceiptPdfInput): Uint8Array {
  const stream = new PdfContentStream()
  drawBackground(stream)
  drawHeader(stream, input)
  drawAmount(stream, input)
  drawReceiptPanel(stream, input)
  drawWatermark(stream)
  drawFooter(stream)

  return buildPdfDocument(stream.toString())
}

function drawBackground(stream: PdfContentStream): void {
  stream.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, '0.050 0.055 0.070')
  stream.rect(32, 32, PAGE_WIDTH - 64, PAGE_HEIGHT - 64, '0.074 0.079 0.098')
  stream.line(32, PAGE_HEIGHT - 98, PAGE_WIDTH - 32, PAGE_HEIGHT - 98, { color: COLORS.border })
  stream.line(32, 116, PAGE_WIDTH - 32, 116, { color: COLORS.border })
}

function drawHeader(stream: PdfContentStream, input: TransferReceiptPdfInput): void {
  stream.text('SONAR', MARGIN_X, PAGE_HEIGHT - 70, { size: 24, font: 'bold', color: COLORS.ink })
  stream.text('BANK', MARGIN_X + 84, PAGE_HEIGHT - 70, { size: 24, font: 'bold', color: COLORS.brand })
  stream.text('Transfer receipt', MARGIN_X, PAGE_HEIGHT - 92, { size: 10, color: COLORS.muted })
  stream.text(input.receipt.status.toUpperCase(), PAGE_WIDTH - MARGIN_X - 90, PAGE_HEIGHT - 70, { size: 10, font: 'bold', color: COLORS.success })
  stream.text(input.timestampLabel, PAGE_WIDTH - MARGIN_X - 130, PAGE_HEIGHT - 91, { size: 9, color: COLORS.muted })
}

function drawAmount(stream: PdfContentStream, input: TransferReceiptPdfInput): void {
  stream.text('Amount sent', MARGIN_X, PAGE_HEIGHT - 154, { size: 11, color: COLORS.muted })
  stream.text(input.amountLabel, MARGIN_X, PAGE_HEIGHT - 195, { size: 38, font: 'bold', color: COLORS.ink })
  stream.text(`To ${input.recipientLabel}`, MARGIN_X, PAGE_HEIGHT - 220, { size: 12, color: COLORS.muted })
}

function drawReceiptPanel(stream: PdfContentStream, input: TransferReceiptPdfInput): void {
  const x = MARGIN_X
  const y = PAGE_HEIGHT - 580
  const w = PAGE_WIDTH - MARGIN_X * 2
  const h = 300
  stream.rect(x, y, w, h, COLORS.panel)
  stream.line(x, y + h, x + w, y + h, { width: 1.4, color: COLORS.brand })

  const rows: Array<[string, string]> = [
    ['Transaction ID', input.receipt.transaction_id],
    ['Correlation ID', input.receipt.correlation_id],
    ['From', input.fromIbanMasked],
    ['To', input.toIbanMasked],
    ['Memo', input.receipt.reason?.trim() || 'No memo'],
    ['Timestamp', input.timestampLabel],
    ['Available balance', formatMinorCurrency(input.receipt.available_balance_minor)],
    ['Idempotency key', input.receipt.idempotency_key],
  ]

  let rowY = y + h - 42
  for (const [label, value] of rows) {
    stream.text(label, x + 24, rowY, { size: 8, color: COLORS.muted })
    stream.text(value, x + 150, rowY, { size: 9, font: 'bold', color: COLORS.ink })
    stream.line(x + 24, rowY - 14, x + w - 24, rowY - 14, { color: COLORS.faint })
    rowY -= 32
  }
}

function drawWatermark(stream: PdfContentStream): void {
  stream.text('SONAR BANK', 188, 396, { size: 34, font: 'bold', color: '0.145 0.150 0.170' })
  stream.text('RECEIPT', 230, 362, { size: 18, font: 'bold', color: '0.145 0.150 0.170' })
}

function drawFooter(stream: PdfContentStream): void {
  stream.text('Generated by SONAR Bank NUI · Financial-grade mock receipt · Keep this receipt for audit reference.', MARGIN_X, 78, { size: 8, color: COLORS.muted })
  stream.text('This document mirrors the client-side C-FE-01 transfer receipt contract.', MARGIN_X, 62, { size: 8, color: COLORS.muted })
}

class PdfContentStream {
  private readonly parts: string[] = []

  text(value: string, x: number, y: number, options: PdfTextOptions = {}): void {
    const size = options.size ?? 10
    const font = options.font === 'bold' ? FONT_BOLD : FONT_REGULAR
    const color = options.color ?? COLORS.ink
    this.parts.push('BT')
    this.parts.push(`${color} rg`)
    this.parts.push(`/${font} ${size} Tf`)
    this.parts.push(`${fixed(x)} ${fixed(y)} Td`)
    this.parts.push(`(${escapePdfText(value)}) Tj`)
    this.parts.push('ET')
  }

  rect(x: number, y: number, width: number, height: number, color: string): void {
    this.parts.push(`${color} rg`)
    this.parts.push(`${fixed(x)} ${fixed(y)} ${fixed(width)} ${fixed(height)} re f`)
  }

  line(x1: number, y1: number, x2: number, y2: number, options: PdfLineOptions = {}): void {
    const width = options.width ?? 0.7
    const color = options.color ?? COLORS.border
    this.parts.push(`${color} RG`)
    this.parts.push(`${fixed(width)} w`)
    this.parts.push(`${fixed(x1)} ${fixed(y1)} m ${fixed(x2)} ${fixed(y2)} l S`)
  }

  toString(): string {
    return this.parts.join('\n')
  }
}

function buildPdfDocument(contentStream: string): Uint8Array {
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${fixed(PAGE_WIDTH)} ${fixed(PAGE_HEIGHT)}] /Resources << /Font << /${FONT_REGULAR} 4 0 R /${FONT_BOLD} 5 0 R >> >> /Contents 6 0 R >>`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    `<< /Length ${byteLength(contentStream)} >>\nstream\n${contentStream}\nendstream`,
  ]

  let body = '%PDF-1.4\n%SONAR\n'
  const offsets = [0]
  objects.forEach((object, index) => {
    offsets.push(byteLength(body))
    body += `${index + 1} 0 obj\n${object}\nendobj\n`
  })

  const xrefOffset = byteLength(body)
  body += `xref\n0 ${objects.length + 1}\n`
  body += '0000000000 65535 f \n'
  for (const offset of offsets.slice(1)) {
    body += `${String(offset).padStart(10, '0')} 00000 n \n`
  }
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return new TextEncoder().encode(body)
}

function buildReceiptFileName(receipt: TransferReceipt): string {
  return `sonar-bank-receipt-${receipt.transaction_id}.pdf`
}

function formatMinorCurrency(amountMinor: number): string {
  return new Intl.NumberFormat('es-ES', {
    style: 'currency',
    currency: 'EUR',
    maximumFractionDigits: 2,
    minimumFractionDigits: 2,
  }).format(amountMinor / 100)
}

function escapePdfText(value: string): string {
  return value.replace(/[\\()]/g, (match) => `\\${match}`).replace(/[\r\n\t]/g, ' ')
}

function fixed(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(2)
}

function byteLength(value: string): number {
  return new TextEncoder().encode(value).length
}
